### ISSUE TITLE
Channel error when loading multi channel dataset on single channel model & multi-channel model

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [Wensi-Tang/OS-CNN#10]
So I trained a multi-channel dataset on a single-channel model and it worked, [see this notebook for reference](https://colab.research.google.com/drive/1SaXl3unSJcVZFqvom-W71gRj9TSXcae6?usp=sharing)
The results though were almost "too good to be true"

Now I tried loading the trained model and executing it on the same dataset but got this error:
`RuntimeError: Given groups=1, weight of size [1024, 1, 1], expected input[1, 16, 4] to have 1 channels, but got 16 channels instead`
[See notebook for reference](https://colab.research.google.com/drive/1qwtkuoQ1BjAPQzDSpwnHXgfZ_Guan8PR?usp=sharing)

I guess this is now related to training a single-channel model with multi-channel data. My question is, why did it even train and is it possible the training model really got 97% accuracy?

For comparison, I also trained a multi-channel model and it only got 66% accuracy on the same dataset. [See notebook for reference](https://colab.research.google.com/drive/1JN_AhejHjk9qwMgq2ZRq0YNwtlMNz3xo?usp=sharing)

I'm also unable to load the multi-channel model
`RuntimeError: Given groups=1, weight of size [4096, 1, 1], expected input[1, 16, 4] to have 1 channels, but got 16 channels instead`
[See notebook for reference](https://colab.research.google.com/drive/1r36hRSYqIIV0XEg1sw_KafUv4hLTH12C?usp=sharing)

**Comment by Wensi-Tang** [comment]
I summarized your questions:
1) The results though were almost "too good to be true"
Haha, your question made me think I am gonna be super-rich. So, I checked you code (not fully run)
You post four links. Let's call them link1, link2, link3 and link4
Code in link1 
despite that, there is the following code in it,
```Python
SEQUENCE_LENGTH = 30
train_sequences = create_sequences(train_df, 'label', SEQUENCE_LENGTH)
test_sequences = create_sequences(test_df, 'label', SEQUENCE_LENGTH)
```
but it seems the model is not using these sequences to run

It still uses
```Python
X_train = np.float32(train_df.iloc[:,:-2].values)
y_train = np.int64(train_df.iloc[:,-1].values)
```
Thus, it can be seen that each data is only a time-series data whose length is 4.
And the four points seem to be [Open, High, Low, Close]. 
Thus, what the model learns is just if Open>Close,  Lable = 1 else Label =0
It's a very simple function.

2)  It on the same dataset but got this error
In the link1, the model is saved to 
```Python
Result_log_folder = './Example_Results_of_OS_CNN/OS_CNN_result_iter_0/'
dataset_name = "btc"
```
But in the link2, the model is  loaded from 
```Python
Result_log_folder = './Results_of_OS_CNN/OS_CNN_result_iter_0/'
```

3)  I also trained a multi-channel model and it only got 66% accuracy on the same dataset. and 4) I'm also unable to load the multi-channel model
I guess (I did not check them carefully), they have the same problems as questions 1) and 2).

PS, I am not sure whether the answer to question 1 makes sense, but if you get super-rich by this in the future, please let me know, and tips are appreciated!

**Comment by Karlheinzniebuhr** [comment]
I'm more than willing to give you a huge tip if this works :)
Ok so you were right I forgot to use the train_sequences, after fixing the results are much less impressive sadly, [only about 50.5% accuracy](https://colab.research.google.com/drive/1kM_j4HzAIdU4cVZuFkipHGSa59a_1qCG?usp=sharing). 

I'm still not sure though if I did the preprocessing correctly. I'm reverse engineering the get_data_and_label_from_ts_file() function now for the multi-channel model and it does not make sense to me so far. As I mentioned [here](https://github.com/Wensi-Tang/OS-CNN/issues/6#issuecomment-1136224837), I don't understand how to generate the number_of_channels.

I'm coming from LSTMs and there at least it works like this, you have your features and your label. And all you need is a row where the last column is your label. This is also how my [CSV](https://drive.google.com/file/d/1vwY2eWz3HzXP7wiUCwC599ivvlnqqmM2/view?usp=sharing) is structured. Any hint on how to generate the model data from that csv for single and multi-channel models I'd hugely appreciate

**Comment by Wensi-Tang** [comment]
Sorry, I am confused about this "I guess this is where shuffling comes in right? To mitigate the test and training set would have to be randomized and shuffled at each epoch?"

If the shuffle operation that you mention is shuffling the whole dataset at each epoch and re-split the train and test data is not correct.

I think the first step might increase the training accuracy to nearly 100%.
There are many hyperparameters that can help with this.

I would suggest increasing the number of epochs maybe 20000,
Change the learning rate [here](https://github.com/Wensi-Tang/OS-CNN/blob/12ab90bdded27f43a864ec4bc1b7264f3ddb2e20/Classifiers/OS_CNN/OS_CNN_easy_use.py#L96)  to 0.01
and patience in scheduler to 500 [here](https://github.com/Wensi-Tang/OS-CNN/blob/12ab90bdded27f43a864ec4bc1b7264f3ddb2e20/Classifiers/OS_CNN/OS_CNN_easy_use.py#L96)

***Question***
1)  What's your expectation baseline? 
I don't have much experience in stock market data, but I think, each decision is 5 min. if we could get 52% accuracy on prediction, the return would be very huge.

2) Is the 52% accuracy calculated by "label 1 / predict 1 "?

**Comment by Karlheinzniebuhr** [comment]
Just finished implementing a trading engine and backtester last month so I'm happy to answer. 

1. Baseline what I expect at least to have some potential is 55% winrate (accuracy)

2. 52% would in theory have a huge compounding effect, in practice though, fees & slippage eat at least 2 or 3%. OS-CNN is promising though, and this is coming from someone who has tried many SOTA ML models already for this market. (This is a compliment to your work btw)
