### ISSUE TITLE
Error while loading multi-channel model

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [Wensi-Tang/OS-CNN#11]
Ok, we are almost there. Getting this error while loading a trained multi-channel model. I integrated to the best of my ability the code you showed us for the BTC pipeline. 
But the load-model pipeline differs from the training pipeline so I'm not sure what I'm missing.
[Check the complete notebook to reproduce](https://colab.research.google.com/drive/1r36hRSYqIIV0XEg1sw_KafUv4hLTH12C?usp=sharing)

```
TypeError: empty() received an invalid combination of arguments - got (tuple, dtype=NoneType, device=NoneType), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.memory_format memory_format, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.memory_format memory_format, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
```

**Comment by Wensi-Tang** [comment]
```Python
layer_parameter_list = generate_layer_parameter_list(1,receptive_field_shape,paramenter_number_of_layer_list)
```
The 1 is the input channel number and it should be 5 "depending on your input channel number"

**Comment by Karlheinzniebuhr** [comment]
Thanks for the fast response. Added that number, now I'm getting this error

![imagen](https://user-images.githubusercontent.com/5278928/170604791-143727bc-5c8a-4fc5-ad08-3c7ef2ebd279.png)

**Comment by Wensi-Tang** [comment]
This part,
```Python
paramenter_number_of_layer_list = [8*128*X_train.shape[1], 5*128*256 + 2*256*128]
Max_kernel_size = 89

# calcualte network structure
receptive_field_shape= min(int(X_train.shape[-1]/4),Max_kernel_size)
print('the shape of inpute data is:',X_train.shape)
print('the max size of kernel is:', receptive_field_shape)
layer_parameter_list = generate_layer_parameter_list(5,receptive_field_shape,paramenter_number_of_layer_list)
print('the Network structure for',dataset_name,'is:')
print(layer_parameter_list)
````

The code I give for pre-processing ***train.shape[-1]*** is 200
But for this ***train.shape[-1]*** is 30 this will influence the size of 
***receptive_field_shape*** for 
***generate_layer_parameter_list()***

**Comment by Karlheinzniebuhr** [comment]
I changed the 200 value to 30 so that should not have been the problem but I noticed that I need to explicitly "put the data to gpu" so I added that part of your example notebook. Now I'm getting an error about size mismatch. Would you please execute the notebook to have a look? I set it up so that it will run out of the box, just click "run all"

**[Notebook](https://colab.research.google.com/drive/1r36hRSYqIIV0XEg1sw_KafUv4hLTH12C?usp=sharing)**

![imagen](https://user-images.githubusercontent.com/5278928/170774893-497d44ef-33c8-42b6-b585-ef42c6183e68.png)

**Comment by Wensi-Tang** [comment]
The Colab is beautifully set!
The layer_parameter_list  should calculated via this:
```Python
layer_parameter_list = generate_layer_parameter_list(1,receptive_field_shape,paramenter_number_of_layer_list,in_channel = 5)
```
the first 1 in it is we want the smallest kernel size to be 1.

Another is 
```Python
data = np.float32(data)
```
