### ISSUE TITLE
Understand model implementation

### ISSUE THREAD

**Issue by Sinnaeve** [Wensi-Tang/OS-CNN#15]
Hello,

I've read your paper and would be interesting to try your model. But I don't understand the implementation. 
What I think I don't get is the mask part.
In OS_CNN.py you use build_layer_with_layer_parameter to create the layers, and in the forward you just use `self.conv1d.weight.data = self.conv1d.weight*self.weight_mask` before applying the conv1d 
It's very unclear for me what this line does.
Is it that you have only one set of weight for convolution with `kernel size = max_kernel_size` (max kernel size being p_k in your paper ?) ans then you apply multiples binary mask that put some weights of the kernel to 0 making its effective size being samller. So the kernel is one big kernel, but the different mask applied make it equivalent to a set of kernel of size [1, ..., max_kernel_size] ?

**Comment by Wensi-Tang** [comment]
Hello, thanks for your attention! 

Your understanding below :

"then you apply multiples binary mask that put some weights of the kernel to 0 making its effective size being smaller. So the kernel is one big kernel, but the different mask applied make it equivalent to a set of kernel of size [1, ..., max_kernel_size] "

is correct.

## The reason for using the mask 
I used the mask to speed up the calculation. It would be faster than using a "for loop" and "concatenate"those results.

The function that I comment on is the original implementation which uses "for loop" and "concatenate".

https://github.com/Wensi-Tang/OS-CNN/blob/5d606f3a32ed6c21cf67a05f4b51163625721a6a/Classifiers/OS_CNN/OS_block.py#L125


I hope my answer can help you. If you have any further questions feel free to tell me!
