### ISSUE TITLE
Question about the parameter input

### ISSUE THREAD

**Issue by qynn12** [Wensi-Tang/OS-CNN#16]
Hello,
I am very interested in your all-scale covering OSCNN, and here is my question about your code.
I've noticed that you set the examples with the `parameter_number_of_layer_list = [8*128*X_train.shape[1], 5*128*256 + 2*256*128]`. I cannot figure out the meaning of each term. And it seems this set would influence the number of output channels in each layer. Can you please give me your reason for such a choice?
I am looking forward to your reply.
Thanks!

**Comment by qynn12** [comment]
Another question is why did you set the last CNN layer of OS-block with the output channel the same as the first layer's?
Thank you again for answering!

**Comment by Wensi-Tang** [comment]
Hello, thanks for your attention! 

For a fair comparison, the parameter_number_of_layer_list = [8*128*X_train.shape[1], 5*128*256 + 2*256*128] is used to keep the model size of each layer the same as that of [FCN](https://arxiv.org/abs/1611.06455). 

You don't need to worry much about this, as Appendix A1 and A2 in the paper show it does not influence the conclusion, whether we fix the model size or channel number.


Below is the explanation for the setting:

The model size cannot be strictly aligned. The model sizes of each layer for FCN are 1*128*8, 128*256*5, and 256*128*3, following this:

The first layer's output channel number (supposing the average kernel size is 50) will be (128*8/50 = 20). 

The second layer's output channel will be (128*256*5/(50*20) = 163). 

For the third layer, its average kernel size is 1.5, and the output channel is around (256*168*3/(163*1.5)=527).

Therefore, if we strictly follow the model size of each layer, the output channel number of each layer increases from 20 to 163 and to 527.

I am not sure whether that setting is good, but it does not follow the 128 to 256 and 128 patterns of FCN. (The FCN's small to large and to small pattern makes more sense to me, I viewed it as mapping to a higher dimension and reducing to a smaller dimension)

There are many ways to balance the channel and model sizes, the way I choose is to move a little bit of the model size from the third layer to the second layer. (So the model size of the second layer is 5*128*256 + 2*256*128). And manually setting the output channel number as the first layer.

As this [example ](https://github.com/Wensi-Tang/OS-CNN/blob/master/Appendix/OS-CNN_network_structure.ipynb) shows, it becomes 100, 220, and 100.

**Comment by qynn12** [comment]
> 

Thanks for your answer! It really helps me a lot.

**Comment by qynn12** [comment]
Thanks for your answer! It really helps me a lot.
