### ISSUE TITLE
How to import modules correctly.

### ISSUE THREAD

**Issue by saath02** [Wensi-Tang/OS-CNN#2]
I was wondering what is the ideal method of importing these modules. Python is not recognizing the path it should take to reach the modules.

**Comment by Wensi-Tang** [comment]
Could you please give me more details, like error message when you run this [file](https://github.com/Wensi-Tang/OS-CNN/blob/master/1_1_OS-CNN_easy_use_Run_and_Save_Model.ipynb)?

I think python 2.0 might have this kind of problem?
My python environment is 3.5.

**Comment by saath02** [comment]
I am on python 3.0. I have downloaded the github repo to my desktop and added an environment variable to the folder of the github repo. However, python is not able to find the module within the folder.

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-14-32f2b3aae30a> in <module>
      1 import os
      2 from os.path import dirname
----> 3 from utils.dataloader.TSC_data_loader import TSC_multivariate_data_loader
      4 from Classifiers.OS_CNN.OS_CNN_easy_use import OS_CNN_easy_use
      5 from sklearn.metrics import accuracy_score

ModuleNotFoundError: No module named 'utils.dataloader'

**Comment by Wensi-Tang** [comment]
It is a problem of importing a file from a relative path
Based on the answer [here ](https://stackoverflow.com/questions/40416072/reading-file-using-relative-path-in-python-project/40416154). The default setting of a relative path is different between  Python3.4+ and Python 3.0.

I recommend you to use the same environment as me or you might meet other problems.

my environment is:
python == 3.5
pytorch == 1.1.0
scikit-learn == 0.21.3.
